ECommerceStore/Controllers/CartController.cs
using ECommerceStore.Models;
using ECommerceStore.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Linq;
using Microsoft.AspNetCore.Authorization;

namespace ECommerceStore.Controllers
{
    public class CartController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IProductRepository _productRepo;
        private Cart _cart;

        public CartController(ILogger<HomeController> logger, IProductRepository productRepository, Cart cart)
        {
            _logger = logger;
            _productRepo = productRepository;
            _cart = cart;
        }

        public IActionResult Index()
        {
            return View(_cart);
        }

        [HttpPost]
        public IActionResult Add(int id, string returnUrl, bool preventRedirect)
        {
            Product product = _productRepo.Products.FirstOrDefault(p => p.Id == id);
            if (product != null)
            {
                _cart.Add(product, 1);
                if (preventRedirect)
                {
                    return Ok();
                }
                else
                {
                    return Redirect(returnUrl);
                }
                
            }
            else
            {
                if (preventRedirect)
                {
                    return BadRequest(new
                    {
                        Error = "Product not found."
                    });
                }
                else
                {
                    return Redirect(returnUrl);
                }
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Remove([FromForm] int id)
        {
            Product product = _productRepo.Products.FirstOrDefault(p => p.Id == id);
            if (product != null)
            {
                _cart.Remove(product);
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Clear()
        {
            _cart.Clear();
            return RedirectToAction(nameof(Index));
        }
    }
}

ECommerceStore/Controllers/OrderController.cs
using ECommerceStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Linq;

namespace ECommerceStore.Controllers
{
    //[Authorize(Roles = "Admins")]
    public class OrderController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IOrderRepository _orderRepo;
        private readonly Cart _cart;

        public OrderController(ILogger<HomeController> logger, IOrderRepository orderRepository, Cart cart)
        {
            _logger = logger;
            _orderRepo = orderRepository;
            _cart = cart;
        }

        public IActionResult Index() => View(_orderRepo.Orders.OrderByDescending(o => o.Id));

        public IActionResult Details([FromRoute]int id)
        {
            Order order = _orderRepo.Orders.FirstOrDefault(o => o.Id == id);
            if (order != null)
            {
                return View(order);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult MarkShipped([FromForm]int id)
        {
            Order order = _orderRepo.Orders.FirstOrDefault(o => o.Id == id);
            if (order != null)
            {
                order.Shipped = true;
                _orderRepo.Save(order);
            }

            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        public IActionResult Checkout() => View();

        [HttpPost]
        [AllowAnonymous]
        public IActionResult Checkout(Order model)
        {
            if (_cart.Items.Count() == 0)
            {
                ModelState.AddModelError(string.Empty, "There are no items in your cart!");
            }

            if (ModelState.IsValid)
            {
                model.CartItems = _cart.Items.ToArray();
                _orderRepo.Save(model);
                _cart.Clear();
                return RedirectToAction("Index", "Payment");
            }
            else
            {
                return View(model);
            }
        }
    }
}

ECommerceStore/Views/Shared/ProductSummary.cshtml
@model ECommerceStore.Models.Product

<div class="col-lg-4">
    <div class="card">
        <img class="card-img-top" src="~/images/@Model.Image" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">@Model.Name</h5>
            <p>@Model.Price.ToString("c")</p>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>

            <form class="addCartForm" asp-controller="Cart" asp-action="Add" method="post">
                <input type="hidden" asp-for="@Model.Id" />
                <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                <button type="submit" class="btn btn-success btn-sm" >Add to cart</button>
            </form>
        </div>
    </div>
</div>

ECommerceStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Order" asp-action="Index">Admin</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Site</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catagory" asp-action="Index">Catagories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="btn btn-sm btn-primary" asp-controller="Account" asp-action="Logout">Log out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/home.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ECommerceStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Store</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            @await Component.InvokeAsync("CartMenuElement")
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ECommerceStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@
    <script src="~/js/home.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>